src/test/java/it/gov/pagopa/fdr/util/AppMessageUtilTest.java

feat: Update_code

---

src/main/resources/application.properties

feat: Fix test

---

src/main/java/it/gov/pagopa/fdr/App.java
src/main/java/it/gov/pagopa/fdr/rest/exceptionmapper/ErrorResponse.java
src/main/java/it/gov/pagopa/fdr/rest/exceptionmapper/ExceptionMappers.java
src/main/java/it/gov/pagopa/fdr/rest/organizations/validation/OrganizationsValidationService.java
src/main/java/it/gov/pagopa/fdr/rest/psps/validation/PspsValidationService.java
src/main/java/it/gov/pagopa/fdr/rest/validation/ListSizeValidator.java
src/main/java/it/gov/pagopa/fdr/service/dto/ReportingFlowGetDto.java
src/main/java/it/gov/pagopa/fdr/service/organizations/InternalOrganizationsService.java
src/main/java/it/gov/pagopa/fdr/service/organizations/OrganizationsService.java

feat: Sonar

---

src/main/java/it/gov/pagopa/fdr/service/organizations/InternalOrganizationsService.java
src/main/java/it/gov/pagopa/fdr/service/organizations/OrganizationsService.java
src/main/java/it/gov/pagopa/fdr/service/psps/PspsService.java
src/main/java/it/gov/pagopa/fdr/util/AppConstant.java
src/main/java/it/gov/pagopa/fdr/util/AppDBUtil.java
src/main/java/it/gov/pagopa/fdr/util/AppMessageUtil.java
src/test/java/it/gov/pagopa/fdr/rest/BaseUnitTestHelper.java
src/test/java/it/gov/pagopa/fdr/rest/info/InfoResourceTest.java
src/test/java/it/gov/pagopa/fdr/rest/organizations/InternalOrganizationResourceIT.java
src/test/java/it/gov/pagopa/fdr/rest/organizations/InternalOrganizationResourceTest.java
src/test/java/it/gov/pagopa/fdr/rest/organizations/OrganizationResourceIT.java
src/test/java/it/gov/pagopa/fdr/rest/organizations/OrganizationResourceTest.java
src/test/java/it/gov/pagopa/fdr/rest/psps/PspResourceIT.java
src/test/java/it/gov/pagopa/fdr/rest/psps/PspResourceTest.java
src/test/java/it/gov/pagopa/fdr/util/AppConstantTestHelper.java

feat: Nod 268 junit tests

---

.quarkus/cli/plugins/quarkus-cli-catalog.json
helm/weu-dev/values-dev.yaml
helm/weu-uat/values-uat.yaml
pom.xml
src/main/java/it/gov/pagopa/fdr/AppStartup.java
src/main/java/it/gov/pagopa/fdr/exception/AppErrorCodeMessageEnum.java
src/main/java/it/gov/pagopa/fdr/rest/filter/RequestFilter.java
src/main/java/it/gov/pagopa/fdr/rest/filter/ResponseFilter.java
src/main/java/it/gov/pagopa/fdr/service/conversion/ConversionService.java
src/main/java/it/gov/pagopa/fdr/service/re/ReService.java
src/main/java/it/gov/pagopa/fdr/service/re/model/BlobHttpBody.java
src/main/java/it/gov/pagopa/fdr/service/re/model/ReInterface.java
src/main/resources/application.properties
src/main/resources/messages.properties
src/test/java/it/gov/pagopa/fdr/test/util/AzuriteResource.java

feat: Nod 343 mandare i payload su storage account

---

src/test/resources/mockserver/cache.json

feat: Fix mock config cache allineato a dev env

---

src/main/java/it/gov/pagopa/fdr/service/conversion/ConversionService.java

feat: set b64 to message queue

---

src/main/java/it/gov/pagopa/fdr/repository/fdr/FdrPaymentInsertEntity.java
src/main/java/it/gov/pagopa/fdr/repository/fdr/FdrPaymentPublishEntity.java
src/main/java/it/gov/pagopa/fdr/service/psps/PspsService.java
src/main/java/it/gov/pagopa/fdr/service/psps/mapper/PspsServiceServiceMapper.java

feat: Add organization to payment

---

src/main/java/it/gov/pagopa/fdr/rest/filter/RequestFilter.java
src/main/java/it/gov/pagopa/fdr/rest/filter/ResponseFilter.java
src/main/java/it/gov/pagopa/fdr/service/psps/PspsService.java

feat: NOD-211 fix re

---

.quarkus/cli/plugins/quarkus-cli-catalog.json
pom.xml
src/main/java/it/gov/pagopa/fdr/service/re/ReService.java
src/test/java/it/gov/pagopa/fdr/service/re/ReServiceTest.java
src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

feat: [NOD-368] new Unit tests for ReService

---

.github/workflows/01_anchore.yml
.github/workflows/04_release_and_deploy.yml

fix: refactored wrong pipelines

---

.github/workflows/04h_deploy_with_github_runner.yml
helm/values-dev.yaml
helm/values-uat.yaml

fix: resolved errors on deploy pipeline

---

pom.xml
src/main/java/it/gov/pagopa/fdr/repository/fdr/FdrPublishEntity.java
src/main/java/it/gov/pagopa/fdr/service/psps/PspsService.java

NOD-545 - fix revision

---

integration-test/features/add_revision_case.feature
integration-test/features/check_fdr_published_case.feature
integration-test/features/check_pageable_org_case.feature
integration-test/features/check_pageable_psp_case.feature
integration-test/features/delete_created_fdr_case.feature
integration-test/features/organization_happy_case.feature
integration-test/features/psp_check_fdr_published_case.feature
integration-test/steps/steps.py
integration-test/steps/utils.py

This Pull Request encapsulates a set of modifications aimed at improving the integration testing.
- Introduction of additional scenarios in the integration tests.
- Corrections to endpoint naming within the utility script.
- Implementation of test steps.
These adjustments are instituted following updates to the endpoint nomenclature in utility scripts, and to fulfill the need for the implementation of additional steps and tests.
The revised integration tests were executed using the behavior-driven development tool, Behave, to assure their effectiveness.
expected)

Integration test fix

---

helm/values-uat.yaml

feart: NOD-642 fix uat

---

src/main/java/it/gov/pagopa/fdr/rest/organizations/BaseOrganizationsResource.java
src/main/java/it/gov/pagopa/fdr/service/conversion/message/FdrMessage.java
src/main/java/it/gov/pagopa/fdr/service/psps/PspsService.java

feat: NOD-642 fix conversion

---

openapi/openapi_internal.json
openapi/openapi_organization.json
openapi/openapi_psp.json
src/main/java/it/gov/pagopa/fdr/repository/fdr/model/PaymentStatusEnumEntity.java
src/main/java/it/gov/pagopa/fdr/rest/model/Payment.java
src/main/java/it/gov/pagopa/fdr/rest/model/PaymentStatusEnum.java
src/main/java/it/gov/pagopa/fdr/service/dto/PaymentStatusEnumDto.java
src/main/java/it/gov/pagopa/fdr/service/re/model/ReInternal.java
src/main/resources/schema-json/fdr_history_schema_v1.json
src/test/java/it/gov/pagopa/fdr/rest/organizations/InternalOrganizationResourceTest.java
src/test/java/it/gov/pagopa/fdr/rest/organizations/OrganizationResourceTest.java
src/test/java/it/gov/pagopa/fdr/rest/psps/InternalPspResourceTest.java
src/test/java/it/gov/pagopa/fdr/rest/psps/PspResourceTest.java
src/test/java/it/gov/pagopa/fdr/test/util/TestUtil.java

NOD-741 aggiunto stato STAND_IN

---

README.md
openapi/openapi_internal.json
openapi/openapi_organization.json
openapi/openapi_psp.json
postman-collection/fdr.postman_collection.json
src/main/java/it/gov/pagopa/fdr/repository/fdr/FdrPaymentInsertEntity.java
src/main/java/it/gov/pagopa/fdr/repository/fdr/FdrPaymentPublishEntity.java
src/main/java/it/gov/pagopa/fdr/rest/model/Payment.java
src/main/java/it/gov/pagopa/fdr/service/dto/PaymentDto.java
src/test/java/it/gov/pagopa/fdr/rest/organizations/InternalOrganizationResourceTest.java
src/test/java/it/gov/pagopa/fdr/rest/organizations/OrganizationResourceTest.java
src/test/java/it/gov/pagopa/fdr/rest/psps/InternalPspResourceTest.java
src/test/java/it/gov/pagopa/fdr/rest/psps/PspResourceTest.java
src/test/java/it/gov/pagopa/fdr/test/util/TestUtil.java

feat: NOD-826 add field idTransit

---

openapi/openapi_internal.json
openapi/openapi_organization.json
openapi/openapi_psp.json
src/main/java/it/gov/pagopa/fdr/repository/fdr/model/PaymentStatusEnumEntity.java
src/main/java/it/gov/pagopa/fdr/rest/model/Payment.java
src/main/java/it/gov/pagopa/fdr/rest/model/PaymentStatusEnum.java
src/main/java/it/gov/pagopa/fdr/service/dto/PaymentStatusEnumDto.java
src/main/resources/schema-json/fdr_history_schema_v1.json
src/test/java/it/gov/pagopa/fdr/rest/organizations/InternalOrganizationResourceTest.java
src/test/java/it/gov/pagopa/fdr/rest/organizations/OrganizationResourceTest.java
src/test/java/it/gov/pagopa/fdr/rest/psps/InternalPspResourceTest.java
src/test/java/it/gov/pagopa/fdr/rest/psps/PspResourceTest.java
src/test/java/it/gov/pagopa/fdr/test/util/TestUtil.java

feat: NOD-875 add STAND_IN_RPT

---

.github/workflows/08_create_dashboard.yml
.opex/env/prod/internal/config.yaml
.opex/env/prod/organization/config.yaml
.opex/env/prod/psp/config.yaml

chore: Alert opex x apim v 2

---

helm/values-dev.yaml
helm/values-uat.yaml
src/main/java/it/gov/pagopa/fdr/service/psps/PspsService.java
src/main/resources/application.properties

[PAGOPA-2282] chore: Update ingress timeout

---

.github/workflows/04_release_and_deploy.yml
.github/workflows/06_integration_test.yml
.identity/.terraform.lock.hcl
.identity/00_data.tf
.identity/03_github_environment.tf

- updated slack webhook secrets reference
Apply `./identity`:
Notify on correct Slack channel
expected)

chore: [PAGOPA-2614] Updated slack webhook

---

pom.xml
src/main/docker/Dockerfile.jvm

update project configuration for sonar
expected)

[PAGOPA-2609] fix: sonar project configs

---

.github/workflows/03_code_review.yml
pom.xml
src/main/docker/Dockerfile.jvm

fix: sonar config on code review workflow
expected)

[PAGOPA-2609] fix: sonar config on code review workflow

---

helm/values-dev.yaml
helm/values-uat.yaml

Add missing `OTEL_RESOURCE_ATTRIBUTES` and `OTEL_SERVICE_NAME` variables for DEV and UAT envs
Add missing `OTEL_RESOURCE_ATTRIBUTES` and `OTEL_SERVICE_NAME` variables for DEV and UAT envs
expected)

fix: add missing OTEL system properties

---

src/main/resources/application.properties

fix log format to include service.name, service.version and service.environment as log fields
fix log format to include service.name, service.version and service.environment as log fields
expected)

fix: ECS format service name, version and env

---

src/main/java/it/gov/pagopa/fdr/repository/FlowToHistoryRepository.java
src/main/java/it/gov/pagopa/fdr/repository/entity/FlowToHistoryEntity.java
src/main/java/it/gov/pagopa/fdr/repository/enums/FlowToHistoryStatusEnum.java
src/main/java/it/gov/pagopa/fdr/service/FlowService.java
src/main/java/it/gov/pagopa/fdr/service/middleware/mapper/FlowToHistoryMapper.java

💾 save a `flow_to_history` entity during publish action
✋ manually
🤖 unit test
expected)

feat(FlowToHistoryMapper.java): implement mapper for FlowToHistoryEntity

---

.github/workflows/04h_deploy_with_github_runner.yml
.identity/.terraform.lock.hcl
.identity/00_data.tf
.identity/03_github_environment.tf
.identity/99_main.tf
helm/Chart.yaml
helm/values-dev.yaml
helm/values-uat.yaml

- Implemented workload identity
- Implemented new runner
- Bump microservices helm chart to 7.1.1
[PAGOPA-2473](https://pagopa.atlassian.net/browse/PAGOPA-2473)
[PAGOPA-2473]: https://pagopa.atlassian.net/browse/PAGOPA-2473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [PAGOPA-2473] Implement workload identity & new runner 

---

.github/workflows/04_release_and_deploy.yml

- fixed GHA release & deploy
expected)

fix: GHA release & deploy

---

.github/workflows/04_release_and_deploy.yml
.github/workflows/04h_deploy_with_github_runner.yml

fix: GHA  deploy

---

helm/values-dev.yaml
helm/values-uat.yaml
src/main/java/it/gov/pagopa/fdr/repository/FlowToHistoryRepository.java
src/main/java/it/gov/pagopa/fdr/repository/entity/FlowToHistoryEntity.java
src/main/java/it/gov/pagopa/fdr/schedule/HistoryCron.java
src/main/resources/application.properties
src/test/java/it/gov/pagopa/fdr/schedule/HistoryCronTest.java
src/test/resources/db-init.sql

refactor(HistoryCron.java): improve flow locking logic

---

.devops/fdr-fase3-db-schema-pipelines.yml

fix: Pipeline schema grant user

---

.devops/fdr-fase3-db-schema-pipelines.yml

fix: Change schema pipeline env injection

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

chore: Fix affinity

---

helm/values-prod.yaml

config(HELM): CPU tuning

---

.github/workflows/08_create_dashboard.yml
.opex/internal/env/prod/config.yaml
.opex/organization/env/prod/config.yaml
.opex/psp/env/prod/config.yaml

This PR resolve the problem with the opex dashboard but I found a bug in the tool https://github.com/pagopa/opex-dashboard/pull/70, for this reason I put the PR **on hold**
- fix opex dashboard
expected)

chore: bump opex dashboard action

---

helm/Chart.yaml

- Bump helm version to 7.5.0
[PIDM-490](https://pagopa.atlassian.net/browse/PIDM-490?atlOrigin=eyJpIjoiOWNhMGQ4MjU1YTU0NDgzMjhhZTY5ZTFkZDJmZGFmMGUiLCJwIjoiaiJ9)
[PIDM-490]: https://pagopa.atlassian.net/browse/PIDM-490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: [PIDM-490] Bump helm version to 7.5.0

---

.devops/fdr-fase3-db-schema-pipelines.yml

chore: Add fdr3r user
